# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79b4513d5c90c80581364fdbfaec34b70d4ea25c47ac6fd4cb41a7b5499033fcedbcb06d07f5f906987479bc87492e632ce2ba1e726ff379b0e546fee143e0e3

test:
  secret_key_base: 11147cd5351e1b950d7d57d1f180c047b91ea185f4f38fdeefbc4739c9570dc067e630c5eef1cce8cb0964a515a92c352245c05996d845885459333d43ab0560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
